In [7]:
from wetterdienst.provider.dwd.observation import DwdObservationRequest
from wetterdienst import Settings
import polars as pl
import pandas as pd

print("Starte DWD-Anfrage...")

# Einstellungen für wetterdienst
settings = Settings(
    ts_shape="long",
    ts_humanize=True,
    ts_convert_units=True
)

# Anfrage initialisieren (ohne Filter)
print("Initialisiere Request für solare Strahlung (10 min)...")
request = DwdObservationRequest(
    parameters=[("10_minutes", "solar", "radiation_global")],
    start_date="2025-01-01",
    end_date="2025-12-31",
    settings=settings
)

# Alle Stationen holen (Metadaten)
print("Lade Stationsliste (Metadaten)...")
all_stations_pl = request.all().df
stations = all_stations_pl.to_pandas()
print(f"-> {len(stations)} Stationen vom DWD erhalten.")

# Datumskonvertierung für Filterung
print("Bereite Datenfilterung vor...")
# KORREKTUR: Spaltennamen 'start_date' und 'end_date' statt 'from_date'/'to_date'
stations['start_date'] = pd.to_datetime(stations['start_date']).dt.tz_localize(None)
stations['end_date'] = pd.to_datetime(stations['end_date']).dt.tz_localize(None)

# Fehlende Enddaten (= aktiv) mit Zukunft füllen
stations['end_date'] = stations['end_date'].fillna(pd.Timestamp.max)

# Filter-Zeitraum definieren (Beispiel: 01.01.2025 bis 31.12.2025)
filter_start = pd.to_datetime("2025-01-01")
filter_end = pd.to_datetime("2025-12-31")
print(f"Filtere Stationen für Zeitraum: {filter_start.date()} bis {filter_end.date()} (GANZ DEUTSCHLAND)")

# Filter anwenden: Station muss VOR Start begonnen haben UND bis NACH Ende aktiv sein
# KEINE Einschränkung auf Bundesländer mehr
filtered_stations = stations[
    (stations['start_date'] <= filter_start) &
    (stations['end_date'] >= filter_end)
    ]

print("-" * 40)
print(f"Gesamtanzahl Stationen (roh): {len(stations)}")
print(f"Anzahl gefilterte Stationen:   {len(filtered_stations)}")
print("-" * 40)

# Ergebnis anzeigen
print("Zeige die ersten 5 Treffer:")
display(filtered_stations[['station_id', 'start_date', 'end_date', 'name', 'state']].head())

Starte DWD-Anfrage...
Initialisiere Request für solare Strahlung (10 min)...
Lade Stationsliste (Metadaten)...
-> 323 Stationen vom DWD erhalten.
Bereite Datenfilterung vor...
Filtere Stationen für Zeitraum: 2025-01-01 bis 2025-12-31 (GANZ DEUTSCHLAND)
----------------------------------------
Gesamtanzahl Stationen (roh): 323
Anzahl gefilterte Stationen:   93
----------------------------------------
Zeige die ersten 5 Treffer:

   station_id start_date   end_date          name                   state
1       00044 2007-04-02 2026-01-17  Großenkneten           Niedersachsen
10      00183 1991-11-01 2026-01-17        Arkona  Mecklenburg-Vorpommern
14      00232 1996-11-07 2026-01-17      Augsburg                  Bayern
20      00342 2010-11-30 2026-01-17          Belm           Niedersachsen
28      00460 1993-09-30 2026-01-17         Berus                Saarland

In [8]:
# --- PRODUKTIV-SKRIPT: SCHLEIFE ÜBER ALLE STATIONEN ---
print("Starte den Download LOOP für alle gefilterten Stationen (ganz Deutschland)...")

station_ids = filtered_stations['station_id'].tolist()
total_stations = len(station_ids)
print(f"Anzahl Stationen zu verarbeiten: {total_stations}")

table_name = 'solar_radiation_2025'
schema_name = 'dwd'

# 1. Tabelle vorbereiten: Vorher löschen, damit wir sauber starten
print(f"Setze Tabelle {schema_name}.{table_name} zurück...")
with engine.connect() as con:
    # Drop table if exists
    con.execute(text(f"DROP TABLE IF EXISTS {schema_name}.{table_name};"))
    
    # Tabelle erstellen (damit wir 'append' nutzen können und Typen festgelegt sind)
    # Wir machen das einfach, indem wir Pandas beim ersten Insert die Tabelle erstellen lassen,
    # ODER wir erstellen sie leer. 
    # Einfachste Strategie für Loop:
    # Erstes Element -> if_exists='replace'
    # Alle weiteren -> if_exists='append'
    pass

print("Start Loop...")

# Schleife über alle Stationen
for i, current_station_id in enumerate(station_ids):
    
    # Fortschrittsanzeige
    print(f"[{i+1}/{total_stations}] Bearbeite Station {current_station_id} ...")
    
    try:
        # A) Request für EINE Station bauen
        request_single = DwdObservationRequest(
            parameters=[("10_minutes", "solar", "radiation_global")],
            start_date="2025-01-01",
            end_date="2025-12-31",
            settings=settings
        ).filter_by_station_id(station_id=[current_station_id])

        # B) Daten laden
        # Wir erwarten ca. 52.560 Zeilen pro Station (bei 10 min Auflösung ganzes Jahr)
        df_single = request_single.values.all().df.to_pandas()
        
        if df_single.empty:
            print(f"   -> WARNUNG: Keine Daten für Station {current_station_id}. Überspringe.")
            continue

        # C) Daten bereinigen
        # Nur Globalstrahlung
        df_solar = df_single[df_single['parameter'] == 'radiation_global'].copy()
        
        # Umbenennen (Einheit beachten: du hast 'joule_per_sqcm' genutzt)
        df_solar = df_solar.rename(columns={
            'date': 'timestamp', 
            'value': 'radiation_global_joule_per_sqcm'
        })
        
        # Spalten wählen
        cols = ['station_id', 'timestamp', 'radiation_global_joule_per_sqcm']
        if 'quality' in df_solar.columns:
            cols.append('quality')
            
        df_final = df_solar[cols]
        
        # D) In DB schreiben
        # Strategie: Wenn es die erste Station ist, 'replace', sonst 'append'
        # Aber da wir oben gedroppt haben, ist 'append' sicherer wenn wir sicherstellen dass sie leer ist,
        # aber Pandas 'replace' erstellt die Tabelle neu.
        # Beste Loop-Strategie mit Pandas:
        # 1. Iteration: if_exists='replace'
        # n. Iteration: if_exists='append'
        
        mode = 'replace' if i == 0 else 'append'
        
        df_final.to_sql(
            table_name, 
            engine, 
            schema=schema_name, 
            if_exists=mode, 
            index=False,
            chunksize=10000 
        )
        
        # Kleines Feedback
        print(f"   -> {len(df_final)} Zeilen gespeichert.")

    except Exception as e:
        print(f"   !!! FEHLER bei Station {current_station_id}: {e}")



print("FERTIG! Alle Daten verarbeitet.")

Starte den Download LOOP für alle gefilterten Stationen (ganz Deutschland)...
Anzahl Stationen zu verarbeiten: 93
Setze Tabelle dwd.solar_radiation_2025 zurück...
Start Loop...
[1/93] Bearbeite Station 00044 ...

No data available for given constraints
Traceback (most recent call last):
  File "c:\Users\user\Projects\Documents\Desktop\MA - BESS\Code\python\.venv\Lib\site-packages\wetterdienst\model\values.py", line 417, in all
    df = pl.concat(data, how="diagonal")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\Projects\Documents\Desktop\MA - BESS\Code\python\.venv\Lib\site-packages\polars\functions\eager.py", line 176, in concat
    raise ValueError(msg)
ValueError: cannot concat empty list

   -> WARNUNG: Keine Daten für Station 00044. Überspringe.
[2/93] Bearbeite Station 00183 ...
   -> 52403 Zeilen gespeichert.
[3/93] Bearbeite Station 00232 ...
   -> 52200 Zeilen gespeichert.
[4/93] Bearbeite Station 00342 ...
   -> 52417 Zeilen gespeichert.
[5/93] Bearbeite Station 00460 ...
   -> 52379 Zeilen gespeichert.
[6/93] Bearbeite Station 00591 ...
   -> 51823 Zeilen gespeichert.
[7/93] Bearbeite Station 00596 ...
   -> 51825 Zeilen gespeichert.
[8/93] Bearbeite Station 00662 ...
   -> 52388 Zeilen gespeichert.
[9/93] Bearbeite Station 00691 ...
   -> 49849 Zeilen gespeichert.
[10/93] Bearbeite Station 00701 ...
   -> 52380 Zeilen gespeichert.
[11/93] Bearbeite Station 00704 ...
   -> 52390 Zeilen gespeichert.
[12/93] Bearbeite Station 00853 ...
   -> 12997 Zeilen gespeichert.
[13/93] Bearbeite Station 00856 ...
   -> 52402 Zeilen gespeichert.
[14/93] Bearbeite Station 00867 ...
   -> 52246 Zeilen gespeichert.
[15/93] Bearbeite Station 00880 ...
   -> 52417 Zeilen gespeichert.
[16/93] Bearbeite Station 00953 ...
   -> 50994 Zeilen gespeichert.
[17/93] Bearbeite Station 00963 ...
   -> 52375 Zeilen gespeichert.
[18/93] Bearbeite Station 01048 ...
   -> 52316 Zeilen gespeichert.
[19/93] Bearbeite Station 01262 ...

No data available for given constraints
Traceback (most recent call last):
  File "c:\Users\user\Projects\Documents\Desktop\MA - BESS\Code\python\.venv\Lib\site-packages\wetterdienst\model\values.py", line 417, in all
    df = pl.concat(data, how="diagonal")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\Projects\Documents\Desktop\MA - BESS\Code\python\.venv\Lib\site-packages\polars\functions\eager.py", line 176, in concat
    raise ValueError(msg)
ValueError: cannot concat empty list

   -> WARNUNG: Keine Daten für Station 01262. Überspringe.
[20/93] Bearbeite Station 01303 ...
   -> 52407 Zeilen gespeichert.
[21/93] Bearbeite Station 01346 ...
   -> 52267 Zeilen gespeichert.
[22/93] Bearbeite Station 01358 ...
   -> 52350 Zeilen gespeichert.
[23/93] Bearbeite Station 01420 ...
   -> 51958 Zeilen gespeichert.
[24/93] Bearbeite Station 01443 ...
   -> 51841 Zeilen gespeichert.
[25/93] Bearbeite Station 01468 ...
   -> 52417 Zeilen gespeichert.
[26/93] Bearbeite Station 01503 ...
   -> 52326 Zeilen gespeichert.
[27/93] Bearbeite Station 01550 ...
   -> 52286 Zeilen gespeichert.
[28/93] Bearbeite Station 01612 ...
   -> 40088 Zeilen gespeichert.
[29/93] Bearbeite Station 01639 ...
   -> 51423 Zeilen gespeichert.
[30/93] Bearbeite Station 01684 ...
   -> 52358 Zeilen gespeichert.
[31/93] Bearbeite Station 01691 ...
   -> 51931 Zeilen gespeichert.
[32/93] Bearbeite Station 01832 ...

No data available for given constraints
Traceback (most recent call last):
  File "c:\Users\user\Projects\Documents\Desktop\MA - BESS\Code\python\.venv\Lib\site-packages\wetterdienst\model\values.py", line 417, in all
    df = pl.concat(data, how="diagonal")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\Projects\Documents\Desktop\MA - BESS\Code\python\.venv\Lib\site-packages\polars\functions\eager.py", line 176, in concat
    raise ValueError(msg)
ValueError: cannot concat empty list

   -> WARNUNG: Keine Daten für Station 01832. Überspringe.
[33/93] Bearbeite Station 01975 ...
   -> 50787 Zeilen gespeichert.
[34/93] Bearbeite Station 02014 ...
   -> 49843 Zeilen gespeichert.
[35/93] Bearbeite Station 02115 ...
   -> 46171 Zeilen gespeichert.
[36/93] Bearbeite Station 02171 ...
   -> 51883 Zeilen gespeichert.
[37/93] Bearbeite Station 02261 ...
   -> 49554 Zeilen gespeichert.
[38/93] Bearbeite Station 02290 ...
   -> 52328 Zeilen gespeichert.
[39/93] Bearbeite Station 02483 ...
   -> 51912 Zeilen gespeichert.
[40/93] Bearbeite Station 02559 ...
   -> 52404 Zeilen gespeichert.
[41/93] Bearbeite Station 02601 ...
   -> 52384 Zeilen gespeichert.
[42/93] Bearbeite Station 02638 ...
   -> 52415 Zeilen gespeichert.
[43/93] Bearbeite Station 02667 ...
   -> 52286 Zeilen gespeichert.
[44/93] Bearbeite Station 02712 ...
   -> 52412 Zeilen gespeichert.
[45/93] Bearbeite Station 02738 ...
   -> 33634 Zeilen gespeichert.
[46/93] Bearbeite Station 02925 ...
   -> 52332 Zeilen gespeichert.
[47/93] Bearbeite Station 02932 ...
   -> 52381 Zeilen gespeichert.
[48/93] Bearbeite Station 02961 ...

No data available for given constraints
Traceback (most recent call last):
  File "c:\Users\user\Projects\Documents\Desktop\MA - BESS\Code\python\.venv\Lib\site-packages\wetterdienst\model\values.py", line 417, in all
    df = pl.concat(data, how="diagonal")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\Projects\Documents\Desktop\MA - BESS\Code\python\.venv\Lib\site-packages\polars\functions\eager.py", line 176, in concat
    raise ValueError(msg)
ValueError: cannot concat empty list

   -> WARNUNG: Keine Daten für Station 02961. Überspringe.
[49/93] Bearbeite Station 03015 ...
   -> 52392 Zeilen gespeichert.
[50/93] Bearbeite Station 03032 ...
   -> 52307 Zeilen gespeichert.
[51/93] Bearbeite Station 03098 ...
   -> 52405 Zeilen gespeichert.
[52/93] Bearbeite Station 03167 ...
   -> 52327 Zeilen gespeichert.
[53/93] Bearbeite Station 03231 ...
   -> 52108 Zeilen gespeichert.
[54/93] Bearbeite Station 03287 ...
   -> 52391 Zeilen gespeichert.
[55/93] Bearbeite Station 03366 ...
   -> 52296 Zeilen gespeichert.
[56/93] Bearbeite Station 03379 ...

No data available for given constraints
Traceback (most recent call last):
  File "c:\Users\user\Projects\Documents\Desktop\MA - BESS\Code\python\.venv\Lib\site-packages\wetterdienst\model\values.py", line 417, in all
    df = pl.concat(data, how="diagonal")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\Projects\Documents\Desktop\MA - BESS\Code\python\.venv\Lib\site-packages\polars\functions\eager.py", line 176, in concat
    raise ValueError(msg)
ValueError: cannot concat empty list

   -> WARNUNG: Keine Daten für Station 03379. Überspringe.
[57/93] Bearbeite Station 03631 ...
   -> 52384 Zeilen gespeichert.
[58/93] Bearbeite Station 03660 ...
   -> 52319 Zeilen gespeichert.
[59/93] Bearbeite Station 03668 ...
   -> 51703 Zeilen gespeichert.
[60/93] Bearbeite Station 03730 ...
   -> 52401 Zeilen gespeichert.
[61/93] Bearbeite Station 03761 ...
   -> 40020 Zeilen gespeichert.
[62/93] Bearbeite Station 03987 ...
   -> 52381 Zeilen gespeichert.
[63/93] Bearbeite Station 04104 ...
   -> 52390 Zeilen gespeichert.
[64/93] Bearbeite Station 04177 ...
   -> 52355 Zeilen gespeichert.
[65/93] Bearbeite Station 04271 ...
   -> 49976 Zeilen gespeichert.
[66/93] Bearbeite Station 04336 ...
   -> 52315 Zeilen gespeichert.
[67/93] Bearbeite Station 04393 ...
   -> 52335 Zeilen gespeichert.
[68/93] Bearbeite Station 04466 ...
   -> 52376 Zeilen gespeichert.
[69/93] Bearbeite Station 04642 ...
   -> 29134 Zeilen gespeichert.
[70/93] Bearbeite Station 04745 ...
   -> 52406 Zeilen gespeichert.
[71/93] Bearbeite Station 04887 ...
   -> WARNUNG: Keine Daten für Station 04887. Überspringe.
[72/93] Bearbeite Station 04928 ...
   -> 52381 Zeilen gespeichert.
[73/93] Bearbeite Station 05029 ...
   -> WARNUNG: Keine Daten für Station 05029. Überspringe.
[74/93] Bearbeite Station 05100 ...
   -> 52300 Zeilen gespeichert.
[75/93] Bearbeite Station 05142 ...
   -> 52410 Zeilen gespeichert.
[76/93] Bearbeite Station 05371 ...
   -> WARNUNG: Keine Daten für Station 05371. Überspringe.
[77/93] Bearbeite Station 05397 ...
   -> 52403 Zeilen gespeichert.
[78/93] Bearbeite Station 05404 ...
   -> 52353 Zeilen gespeichert.
[79/93] Bearbeite Station 05426 ...
   -> 52175 Zeilen gespeichert.
[80/93] Bearbeite Station 05480 ...
   -> 49241 Zeilen gespeichert.
[81/93] Bearbeite Station 05705 ...
   -> 52230 Zeilen gespeichert.
[82/93] Bearbeite Station 05779 ...
   -> 52290 Zeilen gespeichert.
[83/93] Bearbeite Station 05792 ...
   -> 52400 Zeilen gespeichert.
[84/93] Bearbeite Station 05839 ...
   -> 42822 Zeilen gespeichert.
[85/93] Bearbeite Station 05856 ...
   -> 52343 Zeilen gespeichert.
[86/93] Bearbeite Station 05906 ...
   -> 52128 Zeilen gespeichert.
[87/93] Bearbeite Station 06105 ...

No data available for given constraints
Traceback (most recent call last):
  File "c:\Users\user\Projects\Documents\Desktop\MA - BESS\Code\python\.venv\Lib\site-packages\wetterdienst\model\values.py", line 417, in all
    df = pl.concat(data, how="diagonal")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\Projects\Documents\Desktop\MA - BESS\Code\python\.venv\Lib\site-packages\polars\functions\eager.py", line 176, in concat
    raise ValueError(msg)
ValueError: cannot concat empty list

   -> WARNUNG: Keine Daten für Station 06105. Überspringe.
[88/93] Bearbeite Station 06163 ...
   -> 52398 Zeilen gespeichert.
[89/93] Bearbeite Station 06197 ...
   -> 50972 Zeilen gespeichert.
[90/93] Bearbeite Station 07325 ...
   -> 52203 Zeilen gespeichert.
[91/93] Bearbeite Station 07370 ...
   -> 52395 Zeilen gespeichert.
[92/93] Bearbeite Station 15000 ...
   -> 52302 Zeilen gespeichert.
[93/93] Bearbeite Station 15444 ...
   -> 52119 Zeilen gespeichert.
FERTIG! Alle Daten verarbeitet.

In [3]:
import psycopg
from sqlalchemy import create_engine, text
import pandas as pd
from wetterdienst.provider.dwd.observation import DwdObservationRequest
from wetterdienst import Settings

# Verbindung neu aufbauen
db_connection_str = "postgresql+psycopg://postgres:postgres@localhost:5432/redispatch_losses"
engine = create_engine(db_connection_str)

schema_name = 'dwd'
data_table_name = 'solar_radiation_2025' # Tabelle mit den Messdaten
stations_table_name = 'solar_stations_2025' # Zieltabelle für Metadaten

print(f"1. Ermittle Stationen-IDs aus vorhandenen Daten in {schema_name}.{data_table_name} ...")

existing_ids = []
try:
    with engine.connect() as con:
        # Abfrage der IDs, die tatsächlich Daten haben
        result = con.execute(text(f"SELECT DISTINCT station_id FROM {schema_name}.{data_table_name};"))
        existing_ids = [row[0] for row in result]
    print(f" -> {len(existing_ids)} Stationen-IDs in der Datenbank gefunden.")
except Exception as e:
    print(f"Fehler beim Abrufen der IDs: {e}")
    # Hier brechen wir ab, da wir ohne IDs nichts tun können
    raise e

if not existing_ids:
    print("Keine IDs gefunden. Abbruch.")
else:
    print("2. Lade aktuelle Metadaten vom DWD für diese IDs (API-Abfrage)...")
    
    # Einstellungen für Metadaten-Abruf
    settings = Settings(
        ts_shape="long",
        ts_humanize=True,
        ts_convert_units=True
    )
    
    # Request konfigurieren und auf die IDs filtern
    request = DwdObservationRequest(
        parameters=[("10_minutes", "solar", "radiation_global")],
        start_date="2025-01-01", 
        end_date="2025-12-31",
        settings=settings
    ).filter_by_station_id(station_id=existing_ids)
    
    # Metadaten laden (.df property vom Result)
    stations_with_data = request.df.to_pandas()
    
    # Datumsspalten bereinigen (Timezone entfernen für Postgres)
    if 'start_date' in stations_with_data.columns:
        stations_with_data['start_date'] = pd.to_datetime(stations_with_data['start_date']).dt.tz_localize(None)
    if 'end_date' in stations_with_data.columns:
        stations_with_data['end_date'] = pd.to_datetime(stations_with_data['end_date']).dt.tz_localize(None)

    print(f" -> Metadaten für {len(stations_with_data)} Stationen geladen.")
    
    print(f"3. Speichere Metadaten in {schema_name}.{stations_table_name} ...")
    # In DB schreiben
    stations_with_data.to_sql(
        stations_table_name, 
        engine, 
        schema=schema_name, 
        if_exists='replace', # Tabelle neu anlegen
        index=False
    )
    
    # 4. Post-Processing: PK setzen und Geometrie hinzufügen
    with engine.connect() as con:
        try:
            # Primary Key
            con.execute(text(f"ALTER TABLE {schema_name}.{stations_table_name} ADD PRIMARY KEY (station_id);"))
            print("   -> Primary Key gesetzt.")
            
            # Spalte Geom
            con.execute(text(f"ALTER TABLE {schema_name}.{stations_table_name} ADD COLUMN geom geometry(Point, 25832);"))
            print("   -> Spalte 'geom' (EPSG:25832) hinzugefügt.")
    
            # Geometrie berechnen (Long/Lat -> EPSG:25832)
            sql_update = f"""
                UPDATE {schema_name}.{stations_table_name}
                SET geom = ST_Transform(
                    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326),
                    25832
                );
            """
            con.execute(text(sql_update))
            print("   -> Geometrie berechnet und eingetragen.")
            
            # Index
            con.execute(text(f"CREATE INDEX IF NOT EXISTS idx_{stations_table_name}_geom ON {schema_name}.{stations_table_name} USING GIST (geom);"))
            print("   -> Spatial Index erstellt.")
            
            con.commit()
        except Exception as e:
            print(f"   !!! Fehler bei SQL-Nachbearbeitung: {e}")

    print("Fertig.")
    display(stations_with_data.head())

1. Ermittle Stationen-IDs aus vorhandenen Daten in dwd.solar_radiation_2025 ...
 -> 84 Stationen-IDs in der Datenbank gefunden.
2. Lade aktuelle Metadaten vom DWD für diese IDs (API-Abfrage)...
 -> Metadaten für 84 Stationen geladen.
3. Speichere Metadaten in dwd.solar_stations_2025 ...
   -> Primary Key gesetzt.
   -> Spalte 'geom' (EPSG:25832) hinzugefügt.
   -> Geometrie berechnet und eingetragen.
   -> Spatial Index erstellt.
Fertig.

,resolution,dataset,station_id,start_date,end_date,latitude,longitude,height,name,state
0,10_minutes,solar,00183,1991-11-01,2026-01-17,54.6791,13.4344,42.0,Arkona,Mecklenburg-Vorpommern
1,10_minutes,solar,00232,1996-11-07,2026-01-17,48.4253,10.9417,462.0,Augsburg,Bayern
2,10_minutes,solar,00342,2010-11-30,2026-01-17,52.3170,8.1694,103.0,Belm,Niedersachsen
3,10_minutes,solar,00460,1993-09-30,2026-01-17,49.2641,6.6868,362.0,Berus,Saarland
4,10_minutes,solar,00591,1992-04-16,2026-01-17,53.3911,10.6878,45.0,Boizenburg,Mecklenburg-Vorpommern