In [3]:
from wetterdienst.provider.dwd.observation import DwdObservationRequest
from wetterdienst import Settings
import polars as pl
import pandas as pd

print("Starte DWD-Anfrage...")

# Einstellungen für wetterdienst
settings = Settings(
    ts_shape="long",
    ts_humanize=True,
    ts_convert_units=True
)

# Anfrage initialisieren (ohne Filter)
print("Initialisiere Request für Windgeschwindigkeit (10 min)...")
request = DwdObservationRequest(
    parameters=[("10_minutes", "wind", "wind_speed")],
    start_date="2025-01-01",
    end_date="2025-12-31",
    settings=settings
)

# Alle Stationen holen (Metadaten)
print("Lade Stationsliste (Metadaten)...")
all_stations_pl = request.all().df
stations = all_stations_pl.to_pandas()
print(f"-> {len(stations)} Stationen vom DWD erhalten.")

# Datumskonvertierung für Filterung
print("Bereite Datenfilterung vor...")
# KORREKTUR: Spaltennamen 'start_date' und 'end_date' statt 'from_date'/'to_date'
stations['start_date'] = pd.to_datetime(stations['start_date']).dt.tz_localize(None)
stations['end_date'] = pd.to_datetime(stations['end_date']).dt.tz_localize(None)

# Fehlende Enddaten (= aktiv) mit Zukunft füllen
stations['end_date'] = stations['end_date'].fillna(pd.Timestamp.max)

# Filter-Zeitraum definieren (Beispiel: 01.01.2025 bis 31.12.2025)
filter_start = pd.to_datetime("2025-01-01")
filter_end = pd.to_datetime("2025-12-31")
print(f"Filtere Stationen für Zeitraum: {filter_start.date()} bis {filter_end.date()} (GANZ DEUTSCHLAND)")

# Filter anwenden: Station muss VOR Start begonnen haben UND bis NACH Ende aktiv sein
# KEINE Einschränkung auf Bundesländer mehr
filtered_stations = stations[
    (stations['start_date'] <= filter_start) &
    (stations['end_date'] >= filter_end)
    ]

print("-" * 40)
print(f"Gesamtanzahl Stationen (roh): {len(stations)}")
print(f"Anzahl gefilterte Stationen:   {len(filtered_stations)}")
print("-" * 40)

# Ergebnis anzeigen
print("Zeige die ersten 5 Treffer:")
display(filtered_stations[['station_id', 'start_date', 'end_date', 'name', 'state']].head())

Starte DWD-Anfrage...
Initialisiere Request für Windgeschwindigkeit (10 min)...
Lade Stationsliste (Metadaten)...
-> 310 Stationen vom DWD erhalten.
Bereite Datenfilterung vor...
Filtere Stationen für Zeitraum: 2025-01-01 bis 2025-12-31 (GANZ DEUTSCHLAND)
----------------------------------------
Gesamtanzahl Stationen (roh): 310
Anzahl gefilterte Stationen:   276
----------------------------------------
Zeige die ersten 5 Treffer:

,station_id,start_date,end_date,name,state
1,00011,1992-09-17,2026-01-18,Donaueschingen (Landeplatz),Baden-Württemberg
2,00090,1991-01-01,2026-01-17,Alsfeld,Hessen
3,00096,2019-04-09,2026-01-18,Neuruppin-Alt Ruppin,Brandenburg
5,00161,2011-08-30,2026-01-18,Andernach,Rheinland-Pfalz
6,00164,1991-10-31,2026-01-18,Angermünde,Brandenburg

In [4]:
import psycopg
from sqlalchemy import create_engine, text

# Verbindung zur Datenbank
db_connection_str = "postgresql+psycopg://postgres:postgres@localhost:5432/redispatch_losses"
engine = create_engine(db_connection_str)

# --- PRODUKTIV-SKRIPT: SCHLEIFE ÜBER ALLE STATIONEN ---
print("Starte den Download LOOP für alle gefilterten Stationen (ganz Deutschland)...")

station_ids = filtered_stations['station_id'].tolist()
total_stations = len(station_ids)
print(f"Anzahl Stationen zu verarbeiten: {total_stations}")

table_name = 'wind_speed_2025'
schema_name = 'dwd'

# 1. Tabelle vorbereiten: Vorher löschen, damit wir sauber starten
print(f"Setze Tabelle {schema_name}.{table_name} zurück...")
with engine.connect() as con:
    # Drop table if exists
    con.execute(text(f"DROP TABLE IF EXISTS {schema_name}.{table_name};"))
    
    # Tabelle erstellen (damit wir 'append' nutzen können und Typen festgelegt sind)
    # Wir machen das einfach, indem wir Pandas beim ersten Insert die Tabelle erstellen lassen,
    # ODER wir erstellen sie leer. 
    # Einfachste Strategie für Loop:
    # Erstes Element -> if_exists='replace'
    # Alle weiteren -> if_exists='append'
    pass

print("Start Loop...")

# Schleife über alle Stationen
for i, current_station_id in enumerate(station_ids):
    
    # Fortschrittsanzeige
    print(f"[{i+1}/{total_stations}] Bearbeite Station {current_station_id} ...")
    
    try:
        # A) Request für EINE Station bauen
        request_single = DwdObservationRequest(
            parameters=[("10_minutes", "wind", "wind_speed")],
            start_date="2025-01-01",
            end_date="2025-12-31",
            settings=settings
        ).filter_by_station_id(station_id=[current_station_id])

        # B) Daten laden
        # Wir erwarten ca. 52.560 Zeilen pro Station (bei 10 min Auflösung ganzes Jahr)
        df_single = request_single.values.all().df.to_pandas()
        
        if df_single.empty:
            print(f"   -> WARNUNG: Keine Daten für Station {current_station_id}. Überspringe.")
            continue

        # C) Daten bereinigen
        # Nur Windgeschwindigkeit
        df_wind = df_single[df_single['parameter'] == 'wind_speed'].copy()
        
        # Umbenennen
        df_wind = df_wind.rename(columns={
            'date': 'timestamp', 
            'value': 'wind_speed_ms'
        })
        
        # Spalten wählen
        cols = ['station_id', 'timestamp', 'wind_speed_ms']
        if 'quality' in df_wind.columns:
            cols.append('quality')
            
        df_final = df_wind[cols]
        
        # D) In DB schreiben
        # Strategie: Wenn es die erste Station ist, 'replace', sonst 'append'
        # Aber da wir oben gedroppt haben, ist 'append' sicherer wenn wir sicherstellen dass sie leer ist,
        # aber Pandas 'replace' erstellt die Tabelle neu.
        # Beste Loop-Strategie mit Pandas:
        # 1. Iteration: if_exists='replace'
        # n. Iteration: if_exists='append'
        
        mode = 'replace' if i == 0 else 'append'
        
        df_final.to_sql(
            table_name, 
            engine, 
            schema=schema_name, 
            if_exists=mode, 
            index=False,
            chunksize=10000 
        )
        
        # Kleines Feedback
        print(f"   -> {len(df_final)} Zeilen gespeichert.")

    except Exception as e:
        print(f"   !!! FEHLER bei Station {current_station_id}: {e}")



print("FERTIG! Alle Daten verarbeitet.")

Starte den Download LOOP für alle gefilterten Stationen (ganz Deutschland)...
Anzahl Stationen zu verarbeiten: 276
Setze Tabelle dwd.wind_speed_2025 zurück...
Start Loop...
[1/276] Bearbeite Station 00011 ...
   -> 52417 Zeilen gespeichert.
[2/276] Bearbeite Station 00090 ...
   !!! FEHLER bei Station 00090: [WinError 5] Zugriff verweigert: 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache-0u4cujqs' -> 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache'
[3/276] Bearbeite Station 00096 ...
   -> 52417 Zeilen gespeichert.
[4/276] Bearbeite Station 00161 ...
   -> 52356 Zeilen gespeichert.
[5/276] Bearbeite Station 00164 ...
   -> 52417 Zeilen gespeichert.
[6/276] Bearbeite Station 00183 ...
   -> 52417 Zeilen gespeichert.
[7/276] Bearbeite Station 00197 ...
   -> 51684 Zeilen gespeichert.
[8/276] Bearbeite Station 00198 ...
   -> 52417 Zeilen gespeichert.
[9/276] Bearbeite Station 00232 ...
   -> 52166 Zeilen gespeichert.
[10/276] Bearbeite Station 00282 ...
   -> 51030 Zeilen gespeichert.
[11/276] Bearbeite Station 00298 ...
   -> 52417 Zeilen gespeichert.
[12/276] Bearbeite Station 00303 ...
   -> 52407 Zeilen gespeichert.
[13/276] Bearbeite Station 00342 ...
   -> 52417 Zeilen gespeichert.
[14/276] Bearbeite Station 00427 ...
   -> 52151 Zeilen gespeichert.
[15/276] Bearbeite Station 00433 ...
   -> 52417 Zeilen gespeichert.
[16/276] Bearbeite Station 00460 ...
   -> 52386 Zeilen gespeichert.
[17/276] Bearbeite Station 00591 ...
   -> 51920 Zeilen gespeichert.
[18/276] Bearbeite Station 00596 ...
   -> 51748 Zeilen gespeichert.
[19/276] Bearbeite Station 00603 ...
   -> 50137 Zeilen gespeichert.
[20/276] Bearbeite Station 00619 ...
   !!! FEHLER bei Station 00619: [WinError 5] Zugriff verweigert: 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache-2w2vxft4' -> 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache'
[21/276] Bearbeite Station 00642 ...
   -> 52417 Zeilen gespeichert.
[22/276] Bearbeite Station 00656 ...
   -> 52417 Zeilen gespeichert.
[23/276] Bearbeite Station 00662 ...
   -> 52397 Zeilen gespeichert.
[24/276] Bearbeite Station 00691 ...
   -> 52409 Zeilen gespeichert.
[25/276] Bearbeite Station 00701 ...
   -> 51957 Zeilen gespeichert.
[26/276] Bearbeite Station 00704 ...
   -> 52417 Zeilen gespeichert.
[27/276] Bearbeite Station 00722 ...
   -> 52402 Zeilen gespeichert.
[28/276] Bearbeite Station 00788 ...
   !!! FEHLER bei Station 00788: [WinError 5] Zugriff verweigert: 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache-luxa3hqq' -> 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache'
[29/276] Bearbeite Station 00840 ...
   -> 52417 Zeilen gespeichert.
[30/276] Bearbeite Station 00853 ...
   -> 52417 Zeilen gespeichert.
[31/276] Bearbeite Station 00856 ...
   -> 52407 Zeilen gespeichert.
[32/276] Bearbeite Station 00867 ...
   -> 52063 Zeilen gespeichert.
[33/276] Bearbeite Station 00880 ...
   -> 52417 Zeilen gespeichert.
[34/276] Bearbeite Station 00891 ...
   !!! FEHLER bei Station 00891: [Errno 13] Permission denied: 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache'
[35/276] Bearbeite Station 00953 ...
   -> 51066 Zeilen gespeichert.
[36/276] Bearbeite Station 00963 ...
   -> 52389 Zeilen gespeichert.
[37/276] Bearbeite Station 01001 ...
   -> 50825 Zeilen gespeichert.
[38/276] Bearbeite Station 01011 ...
   !!! FEHLER bei Station 01011: [WinError 5] Zugriff verweigert: 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache-gr8vly_8' -> 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache'
[39/276] Bearbeite Station 01013 ...
   -> 51512 Zeilen gespeichert.
[40/276] Bearbeite Station 01048 ...
   -> 52413 Zeilen gespeichert.
[41/276] Bearbeite Station 01078 ...
   -> 51052 Zeilen gespeichert.
[42/276] Bearbeite Station 01200 ...
   -> 52121 Zeilen gespeichert.
[43/276] Bearbeite Station 01262 ...
   -> 51670 Zeilen gespeichert.
[44/276] Bearbeite Station 01270 ...
   !!! FEHLER bei Station 01270: [WinError 5] Zugriff verweigert: 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache-dg82sjmf' -> 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache'
[45/276] Bearbeite Station 01303 ...
   -> 52404 Zeilen gespeichert.
[46/276] Bearbeite Station 01346 ...
   -> 52417 Zeilen gespeichert.
[47/276] Bearbeite Station 01357 ...
   -> 52417 Zeilen gespeichert.
[48/276] Bearbeite Station 01358 ...
   -> 52417 Zeilen gespeichert.
[49/276] Bearbeite Station 01379 ...
   -> 52409 Zeilen gespeichert.
[50/276] Bearbeite Station 01420 ...
   !!! FEHLER bei Station 01420: [WinError 5] Zugriff verweigert: 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache-_7yon4o7' -> 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache'
[51/276] Bearbeite Station 01443 ...
   -> 52357 Zeilen gespeichert.
[52/276] Bearbeite Station 01468 ...
   -> 47680 Zeilen gespeichert.
[53/276] Bearbeite Station 01490 ...
   -> 52417 Zeilen gespeichert.
[54/276] Bearbeite Station 01503 ...
   !!! FEHLER bei Station 01503: [WinError 5] Zugriff verweigert: 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache-e6nmrfl9' -> 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache'
[55/276] Bearbeite Station 01544 ...
   !!! FEHLER bei Station 01544: [WinError 5] Zugriff verweigert: 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache-e5m4jnyi' -> 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache'
[56/276] Bearbeite Station 01550 ...
   -> 49141 Zeilen gespeichert.
[57/276] Bearbeite Station 01580 ...
   -> 51998 Zeilen gespeichert.
[58/276] Bearbeite Station 01587 ...
   -> 52409 Zeilen gespeichert.
[59/276] Bearbeite Station 01605 ...
   !!! FEHLER bei Station 01605: [WinError 5] Zugriff verweigert: 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache-qksb6n1v' -> 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache'
[60/276] Bearbeite Station 01612 ...
   -> 52417 Zeilen gespeichert.
[61/276] Bearbeite Station 01639 ...
   -> 51319 Zeilen gespeichert.
[62/276] Bearbeite Station 01684 ...
   -> 51442 Zeilen gespeichert.
[63/276] Bearbeite Station 01691 ...
   -> 52096 Zeilen gespeichert.
[64/276] Bearbeite Station 01694 ...
   -> 52417 Zeilen gespeichert.
[65/276] Bearbeite Station 01757 ...
   -> 52354 Zeilen gespeichert.
[66/276] Bearbeite Station 01759 ...
   -> 52217 Zeilen gespeichert.
[67/276] Bearbeite Station 01766 ...
   -> 50750 Zeilen gespeichert.
[68/276] Bearbeite Station 01803 ...
   -> 52399 Zeilen gespeichert.
[69/276] Bearbeite Station 01832 ...
   -> 52022 Zeilen gespeichert.
[70/276] Bearbeite Station 01869 ...
   !!! FEHLER bei Station 01869: [WinError 5] Zugriff verweigert: 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache-sdvjdzf7' -> 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache'
[71/276] Bearbeite Station 01886 ...
   !!! FEHLER bei Station 01886: Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
[72/276] Bearbeite Station 01963 ...
   -> 52417 Zeilen gespeichert.
[73/276] Bearbeite Station 01975 ...
   -> 51401 Zeilen gespeichert.
[74/276] Bearbeite Station 01993 ...
   -> 52417 Zeilen gespeichert.
[75/276] Bearbeite Station 02014 ...
   -> 50248 Zeilen gespeichert.
[76/276] Bearbeite Station 02023 ...
   !!! FEHLER bei Station 02023: [WinError 5] Zugriff verweigert: 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache-z4yb85k0' -> 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache'
[77/276] Bearbeite Station 02044 ...
   -> 52417 Zeilen gespeichert.
[78/276] Bearbeite Station 02115 ...
   -> 51728 Zeilen gespeichert.
[79/276] Bearbeite Station 02171 ...
   -> 52294 Zeilen gespeichert.
[80/276] Bearbeite Station 02252 ...
   -> 52399 Zeilen gespeichert.
[81/276] Bearbeite Station 02261 ...
   -> 52345 Zeilen gespeichert.
[82/276] Bearbeite Station 02290 ...
   -> 52388 Zeilen gespeichert.
[83/276] Bearbeite Station 02349 ...
   -> 49763 Zeilen gespeichert.
[84/276] Bearbeite Station 02377 ...
   -> 52417 Zeilen gespeichert.
[85/276] Bearbeite Station 02429 ...
   -> 52395 Zeilen gespeichert.
[86/276] Bearbeite Station 02483 ...
   !!! FEHLER bei Station 02483: [WinError 5] Zugriff verweigert: 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache-p6f8x_cs' -> 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache'
[87/276] Bearbeite Station 02485 ...
   -> 51659 Zeilen gespeichert.
[88/276] Bearbeite Station 02497 ...
   !!! FEHLER bei Station 02497: [WinError 5] Zugriff verweigert: 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache-wvtz2j7o' -> 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache'
[89/276] Bearbeite Station 02559 ...
   -> 52408 Zeilen gespeichert.
[90/276] Bearbeite Station 02564 ...
   -> 52398 Zeilen gespeichert.
[91/276] Bearbeite Station 02573 ...
   -> 52417 Zeilen gespeichert.
[92/276] Bearbeite Station 02597 ...
   -> 51065 Zeilen gespeichert.
[93/276] Bearbeite Station 02601 ...
   -> 51875 Zeilen gespeichert.
[94/276] Bearbeite Station 02638 ...
   -> 52417 Zeilen gespeichert.
[95/276] Bearbeite Station 02667 ...
   !!! FEHLER bei Station 02667: [WinError 5] Zugriff verweigert: 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache-dkjxuy8g' -> 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache'
[96/276] Bearbeite Station 02712 ...
   -> 52144 Zeilen gespeichert.
[97/276] Bearbeite Station 02738 ...
   -> 41688 Zeilen gespeichert.
[98/276] Bearbeite Station 02794 ...
   -> 52353 Zeilen gespeichert.
[99/276] Bearbeite Station 02812 ...
   -> 52349 Zeilen gespeichert.
[100/276] Bearbeite Station 02856 ...
   -> 52417 Zeilen gespeichert.
[101/276] Bearbeite Station 02878 ...
   -> 52387 Zeilen gespeichert.
[102/276] Bearbeite Station 02897 ...
   !!! FEHLER bei Station 02897: [WinError 5] Zugriff verweigert: 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache-3s9r6qup' -> 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache'
[103/276] Bearbeite Station 02907 ...
   -> 51970 Zeilen gespeichert.
[104/276] Bearbeite Station 02925 ...
   -> 52392 Zeilen gespeichert.
[105/276] Bearbeite Station 02928 ...
   -> 52417 Zeilen gespeichert.
[106/276] Bearbeite Station 02932 ...
   -> 52403 Zeilen gespeichert.
[107/276] Bearbeite Station 02961 ...
   -> 51253 Zeilen gespeichert.
[108/276] Bearbeite Station 02985 ...
   -> 52398 Zeilen gespeichert.
[109/276] Bearbeite Station 03015 ...
   -> 52314 Zeilen gespeichert.
[110/276] Bearbeite Station 03028 ...
   -> 51558 Zeilen gespeichert.
[111/276] Bearbeite Station 03032 ...
   -> 52395 Zeilen gespeichert.
[112/276] Bearbeite Station 03086 ...
   -> 52374 Zeilen gespeichert.
[113/276] Bearbeite Station 03093 ...
   -> 52372 Zeilen gespeichert.
[114/276] Bearbeite Station 03098 ...
   -> 52404 Zeilen gespeichert.
[115/276] Bearbeite Station 03126 ...
   -> 52396 Zeilen gespeichert.
[116/276] Bearbeite Station 03158 ...
   -> 51532 Zeilen gespeichert.
[117/276] Bearbeite Station 03166 ...
   -> 52374 Zeilen gespeichert.
[118/276] Bearbeite Station 03167 ...
   -> 52326 Zeilen gespeichert.
[119/276] Bearbeite Station 03196 ...
   -> 50972 Zeilen gespeichert.
[120/276] Bearbeite Station 03231 ...
   -> 52132 Zeilen gespeichert.
[121/276] Bearbeite Station 03244 ...
   -> 52417 Zeilen gespeichert.
[122/276] Bearbeite Station 03268 ...
   -> 52405 Zeilen gespeichert.
[123/276] Bearbeite Station 03287 ...
   -> 52400 Zeilen gespeichert.
[124/276] Bearbeite Station 03321 ...
   -> 51731 Zeilen gespeichert.
[125/276] Bearbeite Station 03362 ...
   -> 52385 Zeilen gespeichert.
[126/276] Bearbeite Station 03366 ...
   -> 52013 Zeilen gespeichert.
[127/276] Bearbeite Station 03376 ...
   -> 52396 Zeilen gespeichert.
[128/276] Bearbeite Station 03379 ...
   -> 51980 Zeilen gespeichert.
[129/276] Bearbeite Station 03402 ...
   -> 52120 Zeilen gespeichert.
[130/276] Bearbeite Station 03513 ...
   -> 52417 Zeilen gespeichert.
[131/276] Bearbeite Station 03534 ...
   -> 52046 Zeilen gespeichert.
[132/276] Bearbeite Station 03631 ...
   -> 52417 Zeilen gespeichert.
[133/276] Bearbeite Station 03651 ...
   !!! FEHLER bei Station 03651: [Errno 13] Permission denied: 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache'
[134/276] Bearbeite Station 03660 ...
   -> 52329 Zeilen gespeichert.
[135/276] Bearbeite Station 03668 ...
   -> 52408 Zeilen gespeichert.
[136/276] Bearbeite Station 03730 ...
   !!! FEHLER bei Station 03730: [WinError 5] Zugriff verweigert: 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache-ym16xjg2' -> 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache'
[137/276] Bearbeite Station 03761 ...
   !!! FEHLER bei Station 03761: [WinError 5] Zugriff verweigert: 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache-9w_3v3vj' -> 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache'
[138/276] Bearbeite Station 03811 ...
   !!! FEHLER bei Station 03811: [WinError 5] Zugriff verweigert: 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache-nglph_84' -> 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache'
[139/276] Bearbeite Station 03821 ...
   -> 52417 Zeilen gespeichert.
[140/276] Bearbeite Station 03897 ...
   -> 52066 Zeilen gespeichert.
[141/276] Bearbeite Station 03905 ...
   -> 52379 Zeilen gespeichert.
[142/276] Bearbeite Station 03925 ...
   -> 52360 Zeilen gespeichert.
[143/276] Bearbeite Station 03946 ...
   !!! FEHLER bei Station 03946: [WinError 5] Zugriff verweigert: 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache-14i0o770' -> 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache'
[144/276] Bearbeite Station 03987 ...
   -> 52407 Zeilen gespeichert.
[145/276] Bearbeite Station 04024 ...
   -> 52404 Zeilen gespeichert.
[146/276] Bearbeite Station 04032 ...
   -> 52406 Zeilen gespeichert.
[147/276] Bearbeite Station 04036 ...
   -> 52412 Zeilen gespeichert.
[148/276] Bearbeite Station 04039 ...
   !!! FEHLER bei Station 04039: [WinError 5] Zugriff verweigert: 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache-t27gfjml' -> 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache'
[149/276] Bearbeite Station 04094 ...
   -> 52417 Zeilen gespeichert.
[150/276] Bearbeite Station 04104 ...
   -> 52159 Zeilen gespeichert.
[151/276] Bearbeite Station 04177 ...
   -> 52355 Zeilen gespeichert.
[152/276] Bearbeite Station 04271 ...
   !!! FEHLER bei Station 04271: [WinError 5] Zugriff verweigert: 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache-0lvwb8ja' -> 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache'
[153/276] Bearbeite Station 04279 ...
   -> 49475 Zeilen gespeichert.
[154/276] Bearbeite Station 04280 ...
   -> 52412 Zeilen gespeichert.
[155/276] Bearbeite Station 04336 ...
   -> 52384 Zeilen gespeichert.
[156/276] Bearbeite Station 04371 ...
   -> 52399 Zeilen gespeichert.
[157/276] Bearbeite Station 04393 ...
   -> 52343 Zeilen gespeichert.
[158/276] Bearbeite Station 04464 ...
   !!! FEHLER bei Station 04464: [WinError 5] Zugriff verweigert: 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache-w_9g9cup' -> 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache'
[159/276] Bearbeite Station 04466 ...
   -> 52374 Zeilen gespeichert.
[160/276] Bearbeite Station 04501 ...
   -> 51236 Zeilen gespeichert.
[161/276] Bearbeite Station 04625 ...
   !!! FEHLER bei Station 04625: [WinError 5] Zugriff verweigert: 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache-wxmuh_j1' -> 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache'
[162/276] Bearbeite Station 04642 ...
   -> 52417 Zeilen gespeichert.
[163/276] Bearbeite Station 04745 ...
   -> 52417 Zeilen gespeichert.
[164/276] Bearbeite Station 04880 ...
   !!! FEHLER bei Station 04880: [WinError 5] Zugriff verweigert: 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache-1hsfa733' -> 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache'
[165/276] Bearbeite Station 04887 ...
   -> 51257 Zeilen gespeichert.
[166/276] Bearbeite Station 04911 ...
   -> 52154 Zeilen gespeichert.
[167/276] Bearbeite Station 04919 ...
   -> 51608 Zeilen gespeichert.
[168/276] Bearbeite Station 04928 ...
   -> 52405 Zeilen gespeichert.
[169/276] Bearbeite Station 04931 ...
   -> 52377 Zeilen gespeichert.
[170/276] Bearbeite Station 04947 ...
   -> 52417 Zeilen gespeichert.
[171/276] Bearbeite Station 05029 ...
   -> 52364 Zeilen gespeichert.
[172/276] Bearbeite Station 05078 ...
   -> 52417 Zeilen gespeichert.
[173/276] Bearbeite Station 05100 ...
   -> 52409 Zeilen gespeichert.
[174/276] Bearbeite Station 05109 ...
   -> 50129 Zeilen gespeichert.
[175/276] Bearbeite Station 05142 ...
   -> 52417 Zeilen gespeichert.
[176/276] Bearbeite Station 05158 ...
   -> 51664 Zeilen gespeichert.
[177/276] Bearbeite Station 05319 ...
   -> 52382 Zeilen gespeichert.
[178/276] Bearbeite Station 05327 ...
   -> 52417 Zeilen gespeichert.
[179/276] Bearbeite Station 05347 ...
   -> 49284 Zeilen gespeichert.
[180/276] Bearbeite Station 05349 ...
   -> 52417 Zeilen gespeichert.
[181/276] Bearbeite Station 05371 ...
   -> 52393 Zeilen gespeichert.
[182/276] Bearbeite Station 05397 ...
   !!! FEHLER bei Station 05397: [WinError 5] Zugriff verweigert: 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache-5wzoq3a3' -> 'C:\\Users\\user\\AppData\\Local\\wetterdienst\\wetterdienst\\Cache\\fsspec\\ttl-FIVE_MINUTES\\cache'
[183/276] Bearbeite Station 05404 ...
   -> 52407 Zeilen gespeichert.
[184/276] Bearbeite Station 05412 ...
   -> 51868 Zeilen gespeichert.
[185/276] Bearbeite Station 05426 ...
   -> 51274 Zeilen gespeichert.
[186/276] Bearbeite Station 05440 ...

In [1]:
import psycopg
from sqlalchemy import create_engine, text
import pandas as pd
import polars as pl
from wetterdienst.provider.dwd.observation import DwdObservationRequest
from wetterdienst import Settings

# Verbindung neu aufbauen
db_connection_str = "postgresql+psycopg://postgres:postgres@localhost:5432/redispatch_losses"
engine = create_engine(db_connection_str)

schema_name = 'dwd'
stations_table_name = 'wind_stations_2025' # Zieltabelle für Metadaten

print("1. Lade alle Stationen vom DWD und filtere auf Jahr 2025...")

# Einstellungen für Metadaten-Abruf
settings = Settings(
    ts_shape="long",
    ts_humanize=True,
    ts_convert_units=True
)

# Request konfigurieren
request = DwdObservationRequest(
    parameters=[("10_minutes", "wind", "wind_speed")],
    start_date="2025-01-01", 
    end_date="2025-12-31",
    settings=settings
)

try:
    # Metadaten laden (.df property vom Result)
    # request.all() liefert alle verfügbaren Stationen
    all_stations_pl = request.all().df
    stations_with_data = all_stations_pl.to_pandas()
    print(f" -> {len(stations_with_data)} Stationen vom DWD erhalten (Gesamt).")
    
    # Datumsspalten bereinigen (Timezone entfernen für Postgres)
    if 'start_date' in stations_with_data.columns:
        stations_with_data['start_date'] = pd.to_datetime(stations_with_data['start_date']).dt.tz_localize(None)
    if 'end_date' in stations_with_data.columns:
        stations_with_data['end_date'] = pd.to_datetime(stations_with_data['end_date']).dt.tz_localize(None)

    # Filter definieren (Konsistent mit vorheriger Logik: Stationen die das GANZE JAHR 2025 abdecken)
    filter_start = pd.to_datetime("2025-01-01")
    filter_end = pd.to_datetime("2025-12-31")
    
    # Hilfsmaske für Filterung (NULL Enddatum = Aktiv bis Zukunft)
    end_date_filled = stations_with_data['end_date'].fillna(pd.Timestamp.max)
    
    mask = (stations_with_data['start_date'] <= filter_start) & (end_date_filled >= filter_end)
    
    filtered_stations = stations_with_data[mask].copy()
    
    print(f" -> {len(filtered_stations)} Stationen verbleiben nach Filterung (Zeitraum 2025).")

    print(f"3. Speichere Metadaten in {schema_name}.{stations_table_name} ...")
    # In DB schreiben
    filtered_stations.to_sql(
        stations_table_name, 
        engine, 
        schema=schema_name, 
        if_exists='replace', # Tabelle neu anlegen
        index=False
    )
    
    # 4. Post-Processing: PK setzen und Geometrie hinzufügen
    with engine.connect() as con:
        # Primary Key
        con.execute(text(f"ALTER TABLE {schema_name}.{stations_table_name} ADD PRIMARY KEY (station_id);"))
        print("   -> Primary Key gesetzt.")
        
        # Spalte Geom
        con.execute(text(f"ALTER TABLE {schema_name}.{stations_table_name} ADD COLUMN geom geometry(Point, 25832);"))
        print("   -> Spalte 'geom' (EPSG:25832) hinzugefügt.")

        # Geometrie berechnen (Long/Lat -> EPSG:25832)
        sql_update = f"""
            UPDATE {schema_name}.{stations_table_name}
            SET geom = ST_Transform(
                ST_SetSRID(ST_MakePoint(longitude, latitude), 4326),
                25832
            );
        """
        con.execute(text(sql_update))
        print("   -> Geometrie berechnet und eingetragen.")
        
        # Index
        con.execute(text(f"CREATE INDEX IF NOT EXISTS idx_{stations_table_name}_geom ON {schema_name}.{stations_table_name} USING GIST (geom);"))
        print("   -> Spatial Index erstellt.")
        
        con.commit()

except Exception as e:
    print(f"Fehler: {e}")
    # raise e # Optional

print("Fertig.")
display(filtered_stations.head())

1. Lade alle Stationen vom DWD und filtere auf Jahr 2025...
 -> 310 Stationen vom DWD erhalten (Gesamt).
 -> 276 Stationen verbleiben nach Filterung (Zeitraum 2025).
3. Speichere Metadaten in dwd.wind_stations_2025 ...
   -> Primary Key gesetzt.
   -> Spalte 'geom' (EPSG:25832) hinzugefügt.
   -> Geometrie berechnet und eingetragen.
   -> Spatial Index erstellt.
Fertig.

,resolution,dataset,station_id,start_date,end_date,latitude,longitude,height,name,state
1,10_minutes,wind,00011,1992-09-17,2026-01-18,47.9736,8.5205,680.0,Donaueschingen (Landeplatz),Baden-Württemberg
2,10_minutes,wind,00090,1991-01-01,2026-01-17,50.7557,9.2583,305.0,Alsfeld,Hessen
3,10_minutes,wind,00096,2019-04-09,2026-01-18,52.9437,12.8518,50.0,Neuruppin-Alt Ruppin,Brandenburg
5,10_minutes,wind,00161,2011-08-30,2026-01-18,50.4237,7.4202,75.0,Andernach,Rheinland-Pfalz
6,10_minutes,wind,00164,1991-10-31,2026-01-18,53.0316,13.9908,54.0,Angermünde,Brandenburg

In [7]:
import pandas as pd
from sqlalchemy import create_engine, text
from wetterdienst.provider.dwd.observation import DwdObservationRequest
from wetterdienst import Settings

# Verbindung
db_connection_str = "postgresql+psycopg://postgres:postgres@localhost:5432/redispatch_losses"
engine = create_engine(db_connection_str)

schema_name = 'dwd'
stations_table = 'wind_stations_2025'
data_table = 'wind_speed_2025'

print("Prüfe auf fehlende Stationen in der Datentabelle...")

# 1. IDs holen
try:
    with engine.connect() as con:
        # Alle erwarteten IDs (aus der bereinigten Stationstabelle)
        res_stations = con.execute(text(f"SELECT station_id FROM {schema_name}.{stations_table}"))
        expected_ids = set([row[0] for row in res_stations])

        # Bereits vorhandene IDs (in der Datentabelle)
        # Checken ob Tabelle existiert
        # Wir gehen davon aus sie existiert, sonst wirft das einen Fehler, den wir fangen könnten.
        res_data = con.execute(text(f"SELECT DISTINCT station_id FROM {schema_name}.{data_table}"))
        existing_ids = set([row[0] for row in res_data])
except Exception as e:
    print(f"Fehler beim DB-Check (evtl. Tabelle noch nicht angelegt?): {e}")
    expected_ids = set()
    existing_ids = set()

# Differenz
missing_ids = list(expected_ids - existing_ids)
missing_ids.sort() # Sortiert für schönere Ausgabe

print(f"Erwartete Stationen (aus {stations_table}): {len(expected_ids)}")
print(f"Vorhandene Stationen (in {data_table}): {len(existing_ids)}")
print(f"-> Fehlende Stationen: {len(missing_ids)}")

if not missing_ids:
    print("Alle Stationen haben bereits Daten. Nichts zu tun.")
else:
    print("Starte Download für fehlende Stationen...")
    
    settings = Settings(
        ts_shape="long",
        ts_humanize=True,
        ts_convert_units=True
    )
    
    count = 0
    total = len(missing_ids)
    
    for station_id in missing_ids:
        count += 1
        print(f"[{count}/{total}] Lade Daten für Station {station_id} ...")
        
        try:
            # Request für eine Station
            request = DwdObservationRequest(
                parameters=[("10_minutes", "wind", "wind_speed")],
                start_date="2025-01-01",
                end_date="2025-12-31",
                settings=settings
            ).filter_by_station_id(station_id=[station_id])
            
            # Daten holen
            result = request.values.all()
            if result.df.is_empty():
                 print(f"   -> Warnung: API lieferte keine Daten.")
                 continue

            df_single = result.df.to_pandas()
            
            if df_single.empty:
                print(f"   -> Keine Daten gefunden (pandas leer).")
                continue
                
            # Filter Windspeed
            # sicherstellen dass Parameter stimmt (manchmal slight variation in naming returned?)
            # parameters=[("10_minutes", "wind", "wind_speed")] -> DWD nennt es 'wind_speed'
            df_wind = df_single[df_single['parameter'] == 'wind_speed'].copy()
            
            if df_wind.empty:
                print("   -> Keine Zeilen für 'wind_speed'.")
                continue

            # Rename Columns
            df_wind = df_wind.rename(columns={
                'date': 'timestamp', 
                'value': 'wind_speed_ms'
            })
            
            # Relevante Spalten
            cols = ['station_id', 'timestamp', 'wind_speed_ms']
            if 'quality' in df_wind.columns:
                cols.append('quality')
            
            df_final = df_wind[cols]
            
            # Speichern (APPEND!)
            df_final.to_sql(
                data_table, 
                engine, 
                schema=schema_name, 
                if_exists='append', 
                index=False,
                chunksize=10000 
            )
            print(f"   -> {len(df_final)} Zeilen eingefügt.")
            
        except Exception as e:
            print(f"   !!! Fehler bei Station {station_id}: {e}")

    print("Fertig mit Nachladen.")

Prüfe auf fehlende Stationen in der Datentabelle...
Erwartete Stationen (aus wind_stations_2025): 276
Vorhandene Stationen (in wind_speed_2025): 276
-> Fehlende Stationen: 0
Alle Stationen haben bereits Daten. Nichts zu tun.

In [ ]:
# --- SQL TEMPLATE FÜR RAUMLICHE INTERPOLATION (IDW) ---
# Das folgende SQL-Statement zeigt, wie du für spezifische Orte und Zeiten
# Werte von den umliegenden Stationen interpolierst.

sql_interpolation = """
WITH basis_daten AS (
    -- Hier deine Tabelle mit den Standorten (Solarparks) und Zeiten
    -- Beispiel: SELECT id, geom, timestamp FROM meine_curtailments
    SELECT 
        p.id AS park_id,
        p.geom AS park_geom,
        p.timestamp As check_time
    FROM 
        solar_parks_events p
),
nearest_stations AS (
    SELECT
        b.park_id,
        b.park_geom,
        s.station_id,
        d.value AS messwert,
        st.geom AS station_geom,
        -- Abstand in Metern (bei projizierten Koordinaten wie EPSG:25832)
        ST_Distance(b.park_geom, st.geom) AS dist
    FROM
        basis_daten b
    CROSS JOIN LATERAL (
        -- MAGIC: Für jeden Park die 5 nächsten Stationen finden, die Daten haben
        SELECT
            st.station_id,
            st.geom,
            dat.value -- Strahlenwert
        FROM
            dwd.solar_stations st
        JOIN
            dwd.solar_data dat ON st.station_id = dat.station_id
        WHERE
            dat.timestamp = b.check_time -- Exakter Zeit-Match (ggf. auf Stunde runden mit date_trunc)
            AND dat.value IS NOT NULL
        ORDER BY
            b.park_geom <-> st.geom -- Nutzt den räumlichen Index (KNN) -> SEHR SCHNELL
        LIMIT 5 -- Anzahl Nachbarn für Interpolation (z.B. 3 bis 5)
    ) s
)
SELECT
    park_id,
    -- Inverse Distance Weighting (IDW): Gewichtung mit 1/dist^2
    -- GREATEST(dist, 1) verhindert Division durch 0, falls Park genau auf Station liegt
    SUM(messwert * (1.0 / power(GREATEST(dist, 1), 2))) / 
    SUM(1.0 / power(GREATEST(dist, 1), 2)) AS interpolated_radiation
FROM
    nearest_stations
GROUP BY
    park_id;
"""

print("SQL-Template definiert. Passe die Tabellennamen an deine Struktur an.")
"""
Hinweise:
1. 'solar_parks_events': Deine Tabelle mit den abzuregelnden Standorten.
2. 'dwd.solar_stations': Deine DWD Stations-Tabelle (mit Geometry).
3. 'dwd.solar_data': Deine DWD Messwerte.
"""

In [ ]:
import psycopg
from sqlalchemy import create_engine, text

# Falls neu gestartet, Verbindung definieren
db_connection_str = "postgresql+psycopg://postgres:postgres@localhost:5432/redispatch_losses"
engine = create_engine(db_connection_str)

schema_name = 'dwd'
data_table_name = 'wind_speed_2025'

print(f"Erstelle Indizes für {schema_name}.{data_table_name} ...")

with engine.begin() as con: # engine.begin() committet automatisch am Ende des Blocks
    # 1. Index auf station_id
    con.execute(text(f"CREATE INDEX IF NOT EXISTS idx_{data_table_name}_station_id ON {schema_name}.{data_table_name} (station_id);"))
    print(f" -> Index auf 'station_id' erstellt.")

    # 2. Index auf timestamp
    con.execute(text(f"CREATE INDEX IF NOT EXISTS idx_{data_table_name}_timestamp ON {schema_name}.{data_table_name} (timestamp);"))
    print(f" -> Index auf 'timestamp' erstellt.")
    
    # 3. Empfehlung: Composite Index (Kombination) für schnelle Abfragen auf (Station + Zeit)
    con.execute(text(f"CREATE INDEX IF NOT EXISTS idx_{data_table_name}_composite ON {schema_name}.{data_table_name} (station_id, timestamp);"))
    print(f" -> Composite Index (station_id, timestamp) erstellt.")

print("Fertig.")